name: Publish to PyPI using uv

on:
  push:
    tags:
      - '*'  # 모든 태그 push 시 작동

permissions:
  id-token: write     # ✅ OIDC 인증에 필요
  contents: write     # ✅ (선택) Release 생성 등에 필요할 수 있음

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pypi.org/p/pycon2025-kyungjun  # Replace <package-name> with your PyPI project name

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build the package using uv
        run: uv build

      - name: Publish to PyPI using uv
        run: uv publish

